import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Footer from "@/components/layouts/Footer";
import Banner from "@/components/landingpage/Banner";
import { ThemeProvider } from "@/components/theme/theme-provider"
import StyledBorder from "@/components/layouts/StyledBorder";
import {Threedots} from "@/components/loaders/Threedots";
import { SeaBoat } from "@/components/loaders/SeaBoat";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Sea Technologies",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased  `}
      >
              <ThemeProvider
            attribute="class"
            defaultTheme="light"
            enableSystem
            disableTransitionOnChange
          >
            {/* <SeaBoat/>
        <Threedots/> */}
        <Banner/>
        {children} 
        <Footer/>
        </ThemeProvider>
      </body>
    </html>
  );
}
